sudo: true
language: node_js
node_js:
  - "8"
  - "10"
  - stable
before_script:
  - npm install -g .
script:
  - cd example && npm install && cd -
  - react-beaker build example
  - react-beaker publish example
